[tool.ruff]
line-length = 100
select = ["E", "F", "W", "I"]  # Select error codes to check
ignore = ["E501"]              # Ignore line length errors (if needed)

[tool.ruff.format]
quote-style = "single"         # Example formatting option
indent-style = "tab"

[tool.ruff.per-file-ignores]
"tests/*" = ["D103", "D100"]  # Ignore some rules in tests
