[tool.ruff]
line-length = 100

[tool.ruff.lint]  # Add this section
    select = ["E", "F", "W", "I"]
    ignore = ["E501", "W191"]  # Add W191 to ignore or change indent-style
    per-file-ignores = {
      "tests/*" = ["D103", "D100"]
    }
[tool.ruff.format]
quote-style = "single"
indent-style = "tab"  # Or "space" if you want to use spaces
