name: Userscript Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Configurer Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16 

      - name: Installer les dépendances
        run: npm ci

      - name: Exécuter les tests
        run: npm test

      - name: Linter
        run: npm run lint -- --max-warnings=0
